language: node_js

node_js:
  - 12.13

cache:
  - npm
  - yarn

git:
  depth: false

branches:
  only:
		- master
		- develop

services:
  - docker

before_script:
	- |
			if [ $TRAVIS_PULL_REQUEST_SLUG == $TRAVIS_REPO_SLUG ]; then
				echo 'Push or Pull Request from same remote branch'
				GIT_DIFF_RESULT=$(eval "$(echo bash diff_checking.sh remotes/origin/$TRAVIS_PULL_REQUEST_BRANCH remotes/origin/develop)")
			else
				echo 'Push or Pull Request from another remote branch'
				eval "$(echo git remote add prBranch https://github.com/$TRAVIS_PULL_REQUEST_SLUG.git)"
				git fetch prBranch develop
				GIT_DIFF_RESULT=$(eval "$(echo bash diff_checking.sh remotes/prBranch/develop remotes/origin/develop)") 
			fi
	- IS_CHANGED_FRONT=$(echo $GIT_DIFF_RESULT | cut -d ',' -f1)
	- IS_CHANGED_BACK=$(echo $GIT_DIFF_RESULT | cut -d ',' -f2)

jobs:
  include:
		#PULL_REQUEST CHECKING STAGE
    - stage: 'DEV TEST'
      name: 'FRONT TEST'
      if: type = pull_request
      script:
        - |
            if [ $IS_CHANGED_FRONT == true ]; then
				  	  echo 'Front test start!'
              cd client
							yarn install
							yarn test
							echo 'test done...'
						else 
							echo 'Front isn't changed...'
						fi

		- name: 'BACK TEST'
			if: type = pull_request
			script:
				- |
						if [ $IS_CHANGED_BACK == true ]; then
							echo 'Back test start!'
							cd server
							yarn install
							echo 'test done...'
						else
							echo 'Back is not changed...'
						fi

    #DEVELOP SERVER BUILD STAGE
		- stage: 'DEV BUILD'
			name: 'DEV SERVER FRONT BUILD'
			if: branch = develop AND type = push
			script:
				- |
						if [ $IS_CHANGED_FRONT == true]; then
							echo 'Develop server front build start!'
							echo 'build done...'
						fi

		- name: 'DEV SERVER BACK BUILD'
			if: branch = develop AND type = push
			script:
				- |
						if [ $IS_CHANGED_BACK == true]; then
							echo 'Develop server back build start!'
							echo 'build done...'
						fi

		#PRODUCT SERVER BUILD STAGE
		- stage: 'PROD BUILD'
			name: 'PROD SERVER FRONT BUILD'
			if: branch = master AND type = push
			script:
				- |
						if [ $IS_CHANGED_FRONT == true]; then
							echo 'Product server front build start!'
							echo 'build done...'
						fi

		- name: 'PROD SERVER BACK BUILD'
			if: branch = master AND type = push
			script:
				- |
						if [ $IS_CHANGED_BACK == true]; then
							echo 'Product server back build start!'
							echo 'build done...'
						fi
