language: node_js

node_js:
  - 12.13

cache:
  - npm
  - yarn

git:
  depth: false

services:
  - docker

branches:
  only:
    - master
    - develop

jobs:
  include:
    #PULL_REQUEST CHECKING STAGE
    - stage: 'TEST'
      name: 'FRONT TEST'
      if: type = pull_request
      before_install:
        - GIT_DIFF_RESULT=$(eval $(echo bash diff_checking.sh $TRAVIS_COMMIT_RANGE))
        - IS_CHANGED_FRONT=$(echo $GIT_DIFF_RESULT | cut -d ',' -f1)
        - |
          if [ $IS_CHANGED_FRONT != true ]; then
            echo 'Front directory not change'
            travis_terminate 0
          fi
        - cd client
      install:
        - yarn install
      script:
        - echo 'Front test start!'
        - yarn test
        - echo 'Front test done...'

    - name: 'BACK TEST'
      if: type = pull_request
      before_install:
        - openssl aes-256-cbc -K $encrypted_09a4eca9209d_key -iv $encrypted_09a4eca9209d_iv -in ./server/.env.enc -out ./server/.env -d
        - GIT_DIFF_RESULT=$(eval $(echo bash diff_checking.sh $TRAVIS_COMMIT_RANGE))
        - IS_CHANGED_BACK=$(echo $GIT_DIFF_RESULT | cut -d ',' -f2)
        - |
          if [ $IS_CHANGED_BACK != true ]; then
            echo 'Back directory not change'
            travis_terminate 0
          fi
      install:
        - yarn install
      script:
        - echo 'Server test start!'
        - npm test
        - echo 'Server test done...'

    #DEVELOP SERVER BUILD STAGE
    - stage: 'DEV BUILD'
      name: 'DEV SERVER FRONT BUILD'
      if: branch = develop AND type = push
      before_script:
        - GIT_DIFF_RESULT=$(eval $(echo bash diff_checking.sh $TRAVIS_COMMIT_RANGE))
        - IS_CHANGED_FRONT=$(echo $GIT_DIFF_RESULT | cut -d ',' -f1)
        - |
          if [ $IS_CHANGED_FRONT != true ]; then
            echo 'Front directory not change'
            travis_terminate 0
          fi
      script: skip

    - name: 'DEV SERVER BACK BUILD'
      if: branch = develop AND type = push
      before_script:
        - openssl aes-256-cbc -K $encrypted_09a4eca9209d_key -iv $encrypted_09a4eca9209d_iv -in ./server/.env.enc -out ./server/.env -d
        - GIT_DIFF_RESULT=$(eval $(echo bash diff_checking.sh $TRAVIS_COMMIT_RANGE))
        - IS_CHANGED_BACK=$(echo $GIT_DIFF_RESULT | cut -d ',' -f2)
        - |
          if [ $IS_CHANGED_BACK != true ]; then
            echo 'Back directory not change'
            travis_terminate 0
          fi
      script: skip

    #PRODUCT SERVER BUILD STAGE
    - stage: 'PROD BUILD'
      name: 'PROD SERVER FRONT BUILD'
      if: branch = master AND type = push
      before_script:
        - GIT_DIFF_RESULT=$(eval $(echo bash diff_checking.sh $TRAVIS_COMMIT_RANGE))
        - IS_CHANGED_FRONT=$(echo $GIT_DIFF_RESULT | cut -d ',' -f1)
        - |
          if [ $IS_CHANGED_FRONT != true ]; then
            echo 'Front directory not change'
            travis_terminate 0
          fi
      script: skip

    - name: 'PROD SERVER BACK BUILD'
      if: branch = master AND type = push
      before_script:
        - openssl aes-256-cbc -K $encrypted_09a4eca9209d_key -iv $encrypted_09a4eca9209d_iv -in ./server/.env.enc -out ./server/.env -d
        - GIT_DIFF_RESULT=$(eval $(echo bash diff_checking.sh $TRAVIS_COMMIT_RANGE))
        - IS_CHANGED_BACK=$(echo $GIT_DIFF_RESULT | cut -d ',' -f2)
        - |
          if [ $IS_CHANGED_BACK != true ]; then
            echo 'Back directory not change'
            travis_terminate 0
          fi
        - sudo apt-get install sshpass
        - docker build -t "$DOCKER_USERNAME/quickkick-api:latest" ./server
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      after_script:
        - docker push "${DOCKER_USERNAME}/quickkick-api:latest
        - sshpass -p "$PROD_SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no root@"$PROD_SERVER_IP" "/home/quickick/api/prod.api.build.sh"
