const actions = {
  SET_MATCH_DAY: 'SET_MATCH_DAY',
  SET_START_TIME: 'SET_START_TIME',
  SET_END_TIME: 'SET_END_TIME',
  SET_SIMILER_RANK: 'SET_SIMILER_RANK',
  INITIALIZE_STATE: 'INITIALIZE_STATE',
};

export default actions;
