const actions = {
  TOGGLE_VIEW_MATCH_REGIST_MODAL: 'TOGGLE_VIEW_MATCH_REGIST_MODAL',
  INSERT_SELECT_DISTRICT: 'INSERT_SELECT_DISTRICT',
  DELETE_SELECT_DISTRICT: 'DELETE_SELECT_DISTRICT',
};

export default actions;
