const actions = {
  TOGGLE_VIEW_MATCH_REGIST_MODAL: 'TOGGLE_VIEW_MATCH_REGIST_MODAL',
  TOGGLE_VIEW_MATCH_APPLY_MODAL: 'TOGGLE_VIEW_MATCH_APPLY_MODAL',
  SELECT_MATCH_INFO: 'SELECT_MATCH_INFO',
  DESELECT_MATCH_INFO: 'DESELECT_MATCH_INFO',
  CLICK_DISTRICT: 'CLICK_DISTRICT',
  INITIALIZE_DISTRICT: 'INITIALIZE_DISTRICT',
};

export default actions;
