const actions = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  SET_IS_UPDATE_TEAM_CODE: 'SET_IS_UPDATE_TEAM_CODE',
  SET_IS_UPDATE_USER_INFO: 'SET_IS_UPDATE_USER_INFO',
  UPDATE_PLAYER_INFO: 'UPDATE_PLAYER_INFO',
};

export default actions;
